# Generated by Django 4.2.7 on 2023-11-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Message',
        ),
    ]
