# Generated by Django 4.2.7 on 2023-12-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_model_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
